version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /gcs
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /s3
    schedule:
      interval: weekly
