name: Go
on:
  push:
    branches: [main]
  pull_request:
jobs:
  check:
    strategy:
      matrix:
        module:
          - .
          - ./gcs
          - ./s3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - id: setup-go
        name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
          check-latest: true
          cache-dependency-path: ${{ matrix.module }}/go.sum
      - name: Verify the Go module
        working-directory: ${{ matrix.module }}
        run: go mod tidy -diff
      - name: Run go vet
        working-directory: ${{ matrix.module }}
        run: go vet ./...
      - name: Run all tests
        working-directory: ${{ matrix.module }}
        run: go test -race -v ./...
